version: '3.1'

services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-test
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      volumes: db-data:/var/lib/mongo/data
  mongo-express:
    image: mongo-express
    container_name: mongo-express-test
    restart: always
    ports:
      - 8081:8082
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSAWORD: 123456
      volumes: db-data:/var/lib/mongo-express/data
